
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bb-app-helm-repo
  namespace: flux-system
spec:
  interval: 10s
  url: https://salahalaoui.github.io/bb-app-helm-charts


---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bb-app-helm-repo2
  namespace: flux-system
spec:
  interval: 10s
  url: oci://ghcr.io/salahalaoui/bb-app/block-buster-helm-app
  secretRef:
    name: flux-system