---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: bb-app
  namespace: flux-system
spec:
  image: docker.io/alaouibs/block-buster-dev
  interval: 10s
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bb-app
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/salahalaoui/ovh
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: bb-app
  namespace: flux-system
spec: 
  imageRepositoryRef:
    name: bb-app
  policy:
    semver: 
      range: 7.8.x
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: bb-app
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: bb-app
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./flux-clusters/prod/bb-app
    strategy: Setters
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bb-app-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: block-buster-helm-app
      version: '7.8.1'
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: bb-app-helm-repo
  install:
    createNamespace: true
  interval: 10s
  storageNamespace: bb-app
  targetNamespace: bb-app
  driftDetection:
    mode: enabled # undo kubectl edits and other unintended changes
  values:
    image:
      # This comment tells Flux to update this field with the full image name (repo:tag)
      repository: docker.io/alaouibs/block-buster-dev:7.8.0 # {"$imagepolicy": "flux-system:bb-app:name"}