---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bb-app-helm-release
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bb-app-helm-repo
  install:
    createNamespace: true
  interval: 10s
  storageNamespace: bb-app
  targetNamespace: bb-app
  values:
    fullnameOverride: ""
    image:
      pullPolicy: Always
      repository: siddharth67/block-buster-dev:7.6.0
      tag: ""
    imagePullSecrets: []
    labels:
      app:
        env: uat
        name: bb-app
        version: 7.x.x
    nameOverride: ""
    namespace:
      name: demo-app
    replicaCount: 1
    service:
      port: 80
      targetPort: 80
      type: ClusterIP
