apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: '38.0.2'
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: traefik
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  interval: 10s
  targetNamespace: traefik
  driftDetection:
    mode: enabled # undo kubectl edits and other unintended changes
  values:
    ingressRoute:
      dashboard:
        enabled: true