apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: flux-system
spec:
  releaseName: vault-secrets-operator
  chart:
    spec:
      chart: vault-secrets-operator
      version: '1.2.0'
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: vault
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  interval: 10s
  storageNamespace: vault-secrets-operator-system
  targetNamespace: vault-secrets-operator-system
  driftDetection:
    mode: enabled # undo kubectl edits and other unintended changes
  values:
    fullnameOverride: "vault-secrets-operator"
    defaultVaultConnection:
      enabled: true
      address: http://vault.vault.svc.cluster.local:8200
      skipTLSVerify: false