apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: '0.32.0'
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: vault
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    force: true
    remediation:
      retries: 3
  interval: 10s
  storageNamespace: vault
  targetNamespace: vault
  driftDetection:
    mode: enabled # undo kubectl edits and other unintended changes
  values:
    fullnameOverride: "vault"
    ui:
      enabled: true
      serviceType: "ClusterIP"
    server:
      ingress:
        enabled: true
        ingressClassName: "traefik"
        pathType: Prefix
        activeService: true
        hosts:
          - host: null
            paths:
              - /
      dev:
        enabled: false
      # Fix permissions on OVH volumes
      securityContext:
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
      ha:
        enabled: true
        replicas: 1
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
            }
            service_registration "kubernetes" {}
      standalone:
        enabled: false
      dataStorage:
        enabled: true
        size: "4Gi"
      auditStorage:
        enabled: true 
        size: "4Gi"
